patch  http://localhost:5000/api/v1/transaction/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTk3NzA1NDc2fQ.fQ8pGKkl6Tn15W-QUxXKhM3CpfD159xcTVS9AM8zNL0

{
  "counterQty": 8,
  "total": 80000000,
  "userId": 3,
  "tripId": 3,
  "status": "Waiting payment",
  "attachment": "bri-syariah.png"
}